
swagger: "2.0"
info:
  version: "1.0.0"
  title: "RAG Text API"
  description: "API for querying text and uploading documents for RAG processing."
host: "localhost:5001"
basePath: "rag_text"
schemes:
  - "http"

paths:
  /query:
    post:
      summary: "Query the RAG text database"
      description: "Send a query to the RAG text database and receive a response."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "JSON object containing the query text."
          required: true
          schema:
            type: "object"
            properties:
              query:
                type: "string"
                example: "What is the capital of France?"
      responses:
        200:
          description: "Query processed successfully."
          schema:
            type: "object"
            properties:
              response:
                type: "string"
        400:
          description: "Invalid input."

  /upload_documents:
    post:
      summary: "Upload PDF documents"
      description: "Upload one or more PDF documents to the server for processing."
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "pdf_files"
          in: "formData"
          description: "PDF files to upload."
          required: true
          type: "array"
          items:
            type: "file"
      responses:
        200:
          description: "Documents uploaded and processed successfully."
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "3 PDF files uploaded and processed successfully."
        400:
          description: "Invalid input or no files uploaded."
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "No file part."
